# Generated by Django 4.0 on 2022-01-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestosnovnestudije',
            name='img_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
