# Generated by Django 4.0 on 2022-01-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0002_alter_vestosnovnestudije_img_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izvor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('godina', models.IntegerField(null=True)),
                ('semestar', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'izvori',
            },
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('vreme', models.DateTimeField()),
                ('link', models.CharField(max_length=255)),
                ('img_link', models.CharField(max_length=255, null=True)),
                ('izvor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vesti.izvor')),
            ],
            options={
                'verbose_name_plural': 'vesti',
            },
        ),
        migrations.DeleteModel(
            name='VestOsnovneStudije',
        ),
    ]
