# Generated by Django 4.0 on 2022-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0003_izvor_vest_delete_vestosnovnestudije'),
    ]

    operations = [
        migrations.AddField(
            model_name='izvor',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
